### ISSUE TITLE
Issue with ios code

### ISSUE THREAD

**Issue by kaciula** [oakleychen0707/flutter_camera_60fps_ios#1]
Hi. Thank you for sharing the code to set the resolution and frame rate.

However, I've encountered an issue:

If I keep opening and closing the camera screen, after a few times, the app crashes with the following error:

`[AVCaptureDevice setActiveVideoMinFrameDuration:] Unsupported frame duration - Supported ranges: ( "<AVFrameRateRange: 0x282eb8f40 1 - 30>" ), tried to set maxFrameRate to 60.000000`

But the iphone does support 60fps. It works correctly when I don't keep opening and closing the camera.

Is there a way to improve the code to not crash in this situation?

**Comment by oakleychen0707** [comment]
Sorry! I'm not quite following your question. Are you saying that sometimes the app crashes after repeatedly pressing record and stop recording?

I've tried recording 13 times, and I haven't encountered the situation you mentioned. Does it require more attempts to happen?

**Comment by kaciula** [comment]
It's not about recording, but about initialization of the camera and the frame rate. It happens if you quickly go back from the camera screen and return and go back again and return. Your example has only one screen so you cannot reproduce it this way.

**Comment by oakleychen0707** [comment]
I see! So now you have two pages switching between each other? And one of them is the recording screen?

**Comment by kaciula** [comment]
Yes. But I don't even start the recording. I just switch back and forth between the pages.

If I comment out the setActiveVideoMinFrameDuration line, it does not crash no matter what I do. But then I don't have any guarantee that the actual frame rate is set to 60 fps.

**Comment by oakleychen0707** [comment]
OK! I'll try to see what you mentioned in a few days.

**Comment by VijayVignesh1** [comment]
Hi,
Even I am facing this issue every time I use 4k/60fps. I am using an iPhone 14 pro max which supports it.

**Comment by oakleychen0707** [comment]
@kaciula 
Hi , I uploaded a new file "second_page.dart". I tried creating two pages, but I didn't encounter the issue you mentioned.

**Comment by oakleychen0707** [comment]
@VijayVignesh1 
Hi, I also tested it using the iPhone 14 Pro Max at 4K/60fps and didn't encounter any issues.

**Comment by kaciula** [comment]
> @kaciula Hi , I uploaded a new file "second_page.dart". I tried creating two pages, but I didn't encounter the issue you mentioned.

@oakleychen0707 You need to add `await setCameraConfiguration(720);` after initializing the camera in second_page.dart. I made it crash this way. Go back and forth between main and second page and it crashes.

![Screenshot 2023-12-05 at 12 31 45](https://github.com/oakleychen0707/flutter_camera_60fps_ios/assets/18688/ac0a6f68-739f-42ff-86f7-0a55cc7cb4fd)

**Comment by oakleychen0707** [comment]
> > @kaciula Hi , I uploaded a new file "second_page.dart". I tried creating two pages, but I didn't encounter the issue you mentioned.
> 
> @oakleychen0707 You need to add `await setCameraConfiguration(720);` after initializing the camera in second_page.dart. I made it crash this way. Go back and forth between main and second page and it crashes.
> 
> ![Screenshot 2023-12-05 at 12 31 45](https://private-user-images.githubusercontent.com/18688/288008271-ac0a6f68-739f-42ff-86f7-0a55cc7cb4fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTUxMjAsIm5iZiI6MTcxMjgxNDgyMCwicGF0aCI6Ii8xODY4OC8yODgwMDgyNzEtYWMwYTZmNjgtNzM5Zi00MmZmLTg2ZjctMGE1NWNjN2NiNGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA1NTM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYTZhMGE0NzI1MGQzYTFiMTVlMGY1NWU2OTlhZjFhNjAzZTEyM2UwZTQ4ZjdjNjNjN2M3ZjVlOTA5YzkyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vPS26PFdIBHTMcudbmzegQxjBGo9f5Lc3QBflyx4EZc)

@kaciula 
Hi, I tried adding the ````await setCameraConfiguration(720);```` you described, and no problems occurred.
